# Generated by Django 5.2 on 2025-04-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
